pined setuptools version to 44.1.0 as Feature support was removed in version 46.0 https://github.com/pypa/setuptools/pull/1979
if not pinned, then the script will fail on import error
 ************************************************************
      sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr1/vahi/pip-install-HUT4hP/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name Feature